baseURL = 'https://blog.spanagiot.gr/'
languageCode = 'en-us'
title = 'DevOps Diaries: A Personal Blog'
theme = 'PaperMod'
[params]
defaultTheme = "dark"
[markup]
  defaultMarkdownHandler = 'goldmark'