baseURL = 'https://blog.spanagiot.gr/'
languageCode = 'en-us'
title = 'DevOps Diaries: A Personal Blog'
theme = 're-terminal'
[params]
defaultTheme = "dark"
themeColor = "orange"
[languages.en.params.logo]
  logoText = "DevOps Diaries @spanagiot"
  logoHomeLink = "/"
[markup]
  defaultMarkdownHandler = 'goldmark'
